name: publish-release-archive
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: create release archive
        shell: bash
        run: 7z a Project_Atlas.7z . '-xr!*.git*' '-xr!workflow'

      - name: publish to nexusmods
        uses: greatness7/nexusmods_file_updater@v2
        with:
          username: ${{secrets.NEXUS_USERNAME}}
          password: ${{secrets.NEXUS_PASSWORD}}
          game_domain_name: "morrowind"
          mod_id: "45399"
          file_name: "Project Atlas"
          file_version: ${{github.ref_name}}
          update_version: true
          file_category: "Main Files"
          new_existing_version: true
          original_file: "^Project Atlas.*"
          remove_old_version: true
          file_description: "Version ${{github.ref_name}}"
          remove_nmm_button: false
          set_as_main_nmm: true
          requirements_pop_up: true
          file_path: "./Project_Atlas.7z"

