name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: compress
        run: 7z a Project_Atlas.7z . '-xr!*.git*'

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: Project_Atlas.7z
